//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fhir.Publication.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fhir.Publication.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ValueSet xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///		&lt;lastUpdated value=&quot;2016-05-26T10:30:30.724+10:00&quot;/&gt;
        ///	&lt;/meta&gt;
        ///  &lt;contained&gt;
        ///    &lt;ConceptMap&gt;
        ///       &lt;id value=&quot;map&quot;/&gt;
        ///      &lt;name value=&quot;NHS Data Model and Dictionary Mapping&quot;/&gt;
        ///      &lt;status value=&quot;draft&quot;/&gt;
        ///      &lt;sourceReference&gt;
        ///        &lt;reference value=&quot;http://hl7.org/fhir/ValueSet/administrative-gender&quot;/&gt;
        ///      &lt;/sourceReference&gt;
        ///      &lt;targetReference&gt;
        ///        &lt;reference value=&quot;http://fhir.nhs.net/Va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Administrative_Gender_1_0 {
            get {
                return ResourceManager.GetString("Administrative_Gender_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;1&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;StructureDefinition/MyBasic&quot; /&gt;
        ///  &lt;name value=&quot;BasicResource&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2015-09-22T20:02:49+10:00&quot; /&gt;
        ///  &lt;description value=&quot;Base StructureDefinition for Ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceAuthorHasZeroCardinality {
            get {
                return ResourceManager.GetString("BasicResourceAuthorHasZeroCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;BasicResource&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table class=&quot;dict&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td colspan=&quot;2&quot; class=&quot;structure&quot;&gt;
        ///        &lt;a name=&quot;Basic&quot;&gt;&lt;/a&gt;
        ///        &lt;b&gt;Basic&lt;/b&gt;
        ///      &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;150px&quot;&gt;Definition&lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;p&gt;Basic is used for handling concepts not yet defined in FHIR, narrative-only resources that don&apos;t map to an existing resource, and custom resources not appropriate for inclusion in the FHIR specificatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceAuthorHasZeroCardinalityHtml {
            get {
                return ResourceManager.GetString("BasicResourceAuthorHasZeroCardinalityHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;1&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;StructureDefinition/MyBasic&quot; /&gt;
        ///  &lt;name value=&quot;MyBasic&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2015-09-22T20:02:49+10:00&quot; /&gt;
        ///  &lt;description value=&quot;Base StructureDefinition for Basic Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceChildElementHasParentWithZeroCardinality {
            get {
                return ResourceManager.GetString("BasicResourceChildElementHasParentWithZeroCardinality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;MyBasic&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table class=&quot;dict&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td colspan=&quot;2&quot; class=&quot;structure&quot;&gt;
        ///        &lt;a name=&quot;Basic&quot;&gt;&lt;/a&gt;
        ///        &lt;b&gt;Basic&lt;/b&gt;
        ///      &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;150px&quot;&gt;Definition&lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;p&gt;Basic is used for handling concepts not yet defined in FHIR, narrative-only resources that don&apos;t map to an existing resource, and custom resources not appropriate for inclusion in the FHIR specification.&lt;/p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceChildElementHasParentWithZeroCardinalityHtml {
            get {
                return ResourceManager.GetString("BasicResourceChildElementHasParentWithZeroCardinalityHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;1&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;StructureDefinition/MyBasic&quot; /&gt;
        ///  &lt;name value=&quot;MyBasic&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2015-09-22T20:02:49+10:00&quot; /&gt;
        ///  &lt;description value=&quot;Base StructureDefinition for Basic Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceIdentifierIsSliced {
            get {
                return ResourceManager.GetString("BasicResourceIdentifierIsSliced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;MyBasic&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table class=&quot;dict&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td colspan=&quot;2&quot; class=&quot;structure&quot;&gt;
        ///        &lt;a name=&quot;Basic&quot;&gt;&lt;/a&gt;
        ///        &lt;b&gt;Basic&lt;/b&gt;
        ///      &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;150px&quot;&gt;Definition&lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;p&gt;Basic is used for handling concepts not yet defined in FHIR, narrative-only resources that don&apos;t map to an existing resource, and custom resources not appropriate for inclusion in the FHIR specification.&lt;/p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceIdentifierIsSlicedHtml {
            get {
                return ResourceManager.GetString("BasicResourceIdentifierIsSlicedHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;1&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;StructureDefinition/MyBasic&quot; /&gt;
        ///  &lt;name value=&quot;BasicResource&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;date value=&quot;2015-09-22T20:02:49+10:00&quot; /&gt;
        ///  &lt;description value=&quot;Base StructureDefinition for Ba [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceNoEdits {
            get {
                return ResourceManager.GetString("BasicResourceNoEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;BasicResource&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table class=&quot;dict&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td colspan=&quot;2&quot; class=&quot;structure&quot;&gt;
        ///        &lt;a name=&quot;Basic&quot;&gt;&lt;/a&gt;
        ///        &lt;b&gt;Basic&lt;/b&gt;
        ///      &lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;150px&quot;&gt;Definition&lt;/td&gt;
        ///      &lt;td&gt;
        ///        &lt;p&gt;Basic is used for handling concepts not yet defined in FHIR, narrative-only resources that don&apos;t map to an existing resource, and custom resources not appropriate for inclusion in the FHIR specificatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicResourceNoEditsHtml {
            get {
                return ResourceManager.GetString("BasicResourceNoEditsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm&quot;&gt;
        ///    &lt;valueInteger value=&quot;4&quot; /&gt;
        ///  &lt;/extension&gt;
        ///  &lt;url value=&quot;urn:x-fhir:uk:nhs:profile:CLCH-BirthNotification-BabyLength&quot; /&gt;
        ///  &lt;version value=&quot;0.0.1&quot; /&gt;
        ///  &lt;name value=&quot;NHS-CLCH-BirthNotification-BabyLength&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BirthNotification_BabyLength {
            get {
                return ResourceManager.GetString("BirthNotification_BabyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///	&lt;meta&gt;
        ///		&lt;lastUpdated value=&quot;2015-04-02T14:21:09.718+02:00&quot; /&gt;
        ///		&lt;tag&gt;
        ///			&lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///			&lt;code value=&quot;baby-patient&quot; /&gt;
        ///			&lt;display value=&quot;baby-patient&quot; /&gt;
        ///		&lt;/tag&gt;
        ///		&lt;tag&gt;
        ///			&lt;system value=&quot;urn:hscic:publishOrder&quot; /&gt;
        ///			&lt;code value=&quot;05&quot; /&gt;
        ///		&lt;/tag&gt;
        ///	&lt;/meta&gt;
        ///	&lt;url value=&quot;http://fhir.nhs.net/StructureDefinition/chis-baby-patient-1-0&quot; /&gt;
        ///	&lt;version value=&quot;1.0&quot; /&gt;
        ///	&lt;name value=&quot;CHIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BirthNotification_BabyPatient {
            get {
                return ResourceManager.GetString("BirthNotification_BabyPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;logical-definition&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;This value set includes codes from the following code systems:&lt;br /&gt;&lt;/p&gt;
        ///  &lt;div class=&quot;import&quot;&gt;
        ///    &lt;div&gt;
        ///      &lt;ul class=&quot;list-unstyled&quot; /&gt;
        ///      &lt;listItems&gt;
        ///        &lt;li&gt;
        ///          &lt;p xmlns=&quot;&quot;&gt;Externally maintained code system: &lt;a href=&quot;http://fhir.nhs.net/ValueSet/sds-job-role-name-1-0&quot;&gt;http://fhir.nhs.net/ValueSet/sds-job-role-name-1-0&lt;/a&gt;&lt;/p&gt;
        ///        &lt;/li&gt;
        ///      &lt;/listItems&gt;
        ///    &lt;/div&gt;
        ///  &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string BulletListforComposeWithImport {
            get {
                return ResourceManager.GetString("BulletListforComposeWithImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;logical-definition&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;This value set includes codes from the following code systems:&lt;br /&gt;&lt;/p&gt;
        ///  &lt;div class=&quot;include&quot;&gt;
        ///    &lt;div&gt;
        ///      &lt;ul class=&quot;list-unstyled&quot; /&gt;
        ///      &lt;listItems&gt;
        ///        &lt;li&gt; Include http://snomed.info/sct where code is 425173008 and display is &apos;record extract (record artifact)&apos;&lt;/li&gt;
        ///      &lt;/listItems&gt;
        ///    &lt;/div&gt;
        ///  &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string BulletListForCompositionWithConcept {
            get {
                return ResourceManager.GetString("BulletListForCompositionWithConcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;logical-definition&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;This value set includes codes from the following code systems:&lt;br /&gt;&lt;/p&gt;
        ///  &lt;div class=&quot;include&quot;&gt;
        ///    &lt;div&gt;
        ///      &lt;ul class=&quot;list-unstyled&quot; /&gt;
        ///      &lt;listItems&gt;
        ///        &lt;li&gt; Include codes from http://snomed.info/sct where concept  in  1391000000139&lt;/li&gt;
        ///      &lt;/listItems&gt;
        ///    &lt;/div&gt;
        ///  &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string BulletListForCompositionWithFilter {
            get {
                return ResourceManager.GetString("BulletListForCompositionWithFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;logical-definition&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;This value set includes codes from the following code systems:&lt;br /&gt;&lt;/p&gt;
        ///  &lt;div class=&quot;include&quot;&gt;
        ///    &lt;div&gt;
        ///      &lt;ul class=&quot;list-unstyled&quot; /&gt;
        ///      &lt;listItems&gt;
        ///        &lt;li&gt; Include codes from http://snomed.info/sct where concept  in  1391000000139&lt;/li&gt;
        ///      &lt;/listItems&gt;
        ///    &lt;/div&gt;
        ///    &lt;div&gt;
        ///      &lt;ul class=&quot;list-unstyled&quot; /&gt;
        ///      &lt;listItems&gt;
        ///        &lt;li&gt; Include http://snomed.info/sct where code is 425173008 and display [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BulletListsForComposeWithImportConceptAndFilter {
            get {
                return ResourceManager.GetString("BulletListsForComposeWithImportConceptAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] config {
            get {
                object obj = ResourceManager.GetObject("config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;&lt;meta&gt;&lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;&lt;/meta&gt;&lt;url value=&quot;http://fhir.nhs.net/StructureDefinition/extension-ers-specialty-1-0&quot; /&gt;&lt;name value=&quot;eRS-Specialty-1-0&quot; /&gt;&lt;status value=&quot;draft&quot; /&gt;&lt;publisher value=&quot;HSCIC&quot; /&gt;&lt;contact&gt;&lt;name value=&quot;Interoperability Team&quot; /&gt;&lt;telecom&gt;&lt;system value=&quot;email&quot; /&gt;&lt;value value=&quot;interoperability@hscic.gov.uk&quot; /&gt;&lt;use value=&quot;work&quot; /&gt;&lt;/telecom&gt;&lt;/contact&gt;&lt;date value=&quot;2015-09-22T20:02:49+10:00&quot; /&gt;&lt;description value=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eRS_Specialty {
            get {
                return ResourceManager.GetString("eRS_Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;CHIS-BabyPatient-Patient-1-0&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table class=&quot;dict&quot; width=&quot;100%&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td id=&quot;CHIS-BabyPatient-Patient-1-0&quot; width=&quot;150px&quot; class=&quot;structure&quot;&gt;
        ///        &lt;a exampleName=&quot;CHIS-BabyPatient-Patient-1-0&quot;&gt;&lt;/a&gt;
        ///        &lt;b&gt;Examples&lt;/b&gt;
        ///      &lt;/td&gt;
        ///      &lt;td class=&quot;structure&quot;&gt;Description&lt;/td&gt;
        ///      &lt;td width=&quot;100px&quot; class=&quot;structure&quot;&gt;XML File&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;150px&quot;&gt;baby-patient&lt;/td&gt;
        ///      &lt;td&gt;baby-patient [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExamplesIndex2Examples {
            get {
                return ResourceManager.GetString("ExamplesIndex2Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;example-table&quot;&gt;
        ///  &lt;p&gt;
        ///    &lt;b&gt;GPConnect Location&lt;/b&gt;
        ///  &lt;/p&gt;
        ///  &lt;table&gt;
        ///    &lt;tr xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      &lt;th class=&quot;col-name&quot;&gt;Examples&lt;/th&gt;
        ///      &lt;th class=&quot;col-description&quot;&gt;Description&lt;/th&gt;
        ///      &lt;th class=&quot;col-xml-file&quot;&gt;XML File&lt;/th&gt;
        ///      &lt;th class=&quot;col-json-file&quot;&gt;JSON File&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///      &lt;tr /&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Location-1a&lt;/td&gt;
        ///        &lt;td /&gt;Location Example - Physiotherapy Clinic&lt;td&gt;
        ///          &lt;a targ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleTabTableIsAlphabetical {
            get {
                return ResourceManager.GetString("ExampleTabTableIsAlphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://fhir.nhs.net/StructureDefinition/extension-ethnic-category-1-0&quot; /&gt;
        ///  &lt;version value=&quot;1.0&quot; /&gt;
        ///  &lt;name value=&quot;Extension-EthnicCategory-1-0&quot; /&gt;
        ///  &lt;status value=&quot;draft&quot; /&gt;
        ///  &lt;publisher value=&quot;HSCIC&quot; /&gt;
        ///  &lt;contact&gt;
        ///    &lt;telecom&gt;
        ///      &lt;system value=&quot;email&quot; /&gt;
        ///      &lt;value value=&quot;interoperabilityteam@hscic.gov.uk&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Extension_EthnicCategory {
            get {
                return ResourceManager.GetString("Extension_EthnicCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;Minimum and maximum # of times the element can appear in the instance&quot;&gt;Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtensionSnaphotElementWithShortDescription {
            get {
                return ResourceManager.GetString("ExtensionSnaphotElementWithShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;binding-description&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;The codes SHALL be taken from &lt;a href=&quot;http://myUri&quot;&gt;http://myUri&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string FhirUriBinding {
            get {
                return ResourceManager.GetString("FhirUriBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;Minimum and maximum # of times the element can appear in the instance&quot;&gt;Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FourXFourHtmlTable {
            get {
                return ResourceManager.GetString("FourXFourHtmlTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The following operation definitions are available in this profile.&lt;/p&gt;&lt;table border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; width=&quot;100%&quot; style=&quot;border: 0px; font-size: 11px; font-family: verdana; vertical-align: top;&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;&lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;&lt;th class=&quot;heirarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px; width:250px&quot;&gt;&lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/spa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneratedProfilePage {
            get {
                return ResourceManager.GetString("GeneratedProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-09-22T20:02:49.724+10:00&quot; /&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;Composition-CareRecord&quot; /&gt;
        ///      &lt;display value=&quot;NHS Patient Care Record&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:publishOrder&quot; /&gt;
        ///      &lt;code value=&quot;4&quot; /&gt;
        ///    &lt;/tag&gt;
        ///  &lt;/meta&gt;
        ///  &lt;extension url=&quot;http://hl7.org/fhir/StructureDefinition/structuredefinition [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPConnect_CareRecord_Composition_1_0 {
            get {
                return ResourceManager.GetString("GPConnect_CareRecord_Composition_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-04-02T14:21:09.718+02:00&quot; /&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:publishOrder&quot; /&gt;
        ///      &lt;code value=&quot;21&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;Location-1a&quot; /&gt;
        ///      &lt;display value=&quot;Hematology clinic&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;Location-1b&quot; /&gt;
        ///      &lt;displ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPConnect_Location_1_0 {
            get {
                return ResourceManager.GetString("GPConnect_Location_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-04-02T14:21:09.718+02:00&quot; /&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;Patient&quot; /&gt;
        ///      &lt;display value=&quot;NHS Patient example&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:publishOrder&quot; /&gt;
        ///      &lt;code value=&quot;3&quot; /&gt;
        ///    &lt;/tag&gt;
        ///  &lt;/meta&gt;
        ///  &lt;url value=&quot;http://fhir.nhs.net/StructureDefinition/gpconnect-patient-1-0&quot; /&gt;
        ///  &lt;version valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPConnect_Patient_1_0 {
            get {
                return ResourceManager.GetString("GPConnect_Patient_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;StructureDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;meta&gt;
        ///    &lt;lastUpdated value=&quot;2015-04-02T14:21:09.718+02:00&quot; /&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:publishOrder&quot; /&gt;
        ///      &lt;code value=&quot;20&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;GP Practitioner&quot; /&gt;
        ///      &lt;display value=&quot;GP Practitioner example&quot; /&gt;
        ///    &lt;/tag&gt;
        ///    &lt;tag&gt;
        ///      &lt;system value=&quot;urn:hscic:examples&quot; /&gt;
        ///      &lt;code value=&quot;Practitioner&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GPConnect_Practitioner_1_0 {
            get {
                return ResourceManager.GetString("GPConnect_Practitioner_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ImplementationGuide xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ExamplesXML&quot;&gt;
        ///		&lt;valueBoolean value=&quot;true&quot; /&gt;
        ///	&lt;/extension&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ExamplesJSON&quot;&gt;
        ///		&lt;valueBoolean value=&quot;true&quot; /&gt;
        ///	&lt;/extension&gt;
        ///  	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ValuesetsXML&quot;&gt;
        ///		&lt;valueBoolean value=&quot;true&quot; /&gt;
        ///	&lt;/extension&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ValuesetsJSON&quot;&gt;
        ///		&lt;valueBoolean value=&quot;true&quot; /&gt;
        ///	&lt;/extension&gt;
        ///  &lt;extension url=&quot;u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGResource {
            get {
                return ResourceManager.GetString("IGResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ImplementationGuide xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ExamplesXML&quot;&gt;
        ///		&lt;valueBoolean value=&quot;true&quot; /&gt;
        ///	&lt;/extension&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-ExamplesJSON&quot;&gt;
        ///		&lt;valueBoolean value=&quot;false&quot; /&gt;
        ///	&lt;/extension&gt;
        ///	&lt;extension url=&quot;urn:fhir.nhs.uk:extension/IG-OnlineVersion&quot;&gt;
        ///		&lt;valueBoolean value=&quot;false&quot; /&gt;
        ///	&lt;/extension&gt;
        ///  &lt;extension url=&quot;urn:fhir.nhs.uk:extension/Schemas&quot;&gt;
        ///    &lt;valueBoolean value=&quot;true&quot; /&gt;
        ///  &lt;/extension&gt;
        ///	&lt;extension url=&quot;urn:fh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IGResource2Packages {
            get {
                return ResourceManager.GetString("IGResource2Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;binding-description&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;The codes SHALL be taken from &lt;a href=&quot;message-event-2-0.html&quot;&gt;http://fhir.nhs.net/ValueSet/message-event-2-0&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string localLinkBindingDescription {
            get {
                return ResourceManager.GetString("localLinkBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;OperationDefinition xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///	&lt;url value=&quot;http://fhir.nhs.net/OperationDefinition/ers-MyOperation-1-0&quot; /&gt;
        ///	&lt;name value=&quot;MyOperation&quot; /&gt;
        ///	&lt;status value=&quot;active&quot; /&gt;
        ///	&lt;kind value=&quot;query&quot; /&gt;
        ///	&lt;description value=&quot;This is the second of my test operations for the publisher&quot; /&gt;
        ///	&lt;code value=&quot;MyOperation&quot; /&gt;
        ///	&lt;system value=&quot;false&quot; /&gt;
        ///	&lt;type value=&quot;HealthcareService&quot; /&gt;
        ///	&lt;instance value=&quot;true&quot; /&gt;
        ///	&lt;parameter&gt;
        ///		&lt;name value=&quot;patientNhsNumber&quot; /&gt;
        ///		&lt;use value=&quot;in&quot; /&gt;
        ///		&lt;min value=&quot;1&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MyOperation {
            get {
                return ResourceManager.GetString("MyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;Minimum and maximum # of times the element can appear in the instance&quot;&gt;Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonSlicedSnapshotElementWithShortDescription {
            get {
                return ResourceManager.GetString("NonSlicedSnapshotElementWithShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px; width:100px&quot;&gt;
        ///      &lt;span title=&quot;The path of the element&quot;&gt;Path&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px; width:100px&quot;&gt;
        ///      &lt;span title=&quot;The name of the valueSet&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OperationDefinitionBindingsTabTable {
            get {
                return ResourceManager.GetString("OperationDefinitionBindingsTabTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ProcedureRequest xmlns=&quot;http://hl7.org/fhir&quot;&gt;
        ///  &lt;id value=&quot;example&quot;/&gt;
        ///  &lt;text&gt;
        ///    &lt;status value=&quot;generated&quot;/&gt;
        ///    &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;To be added&lt;/div&gt;
        ///  &lt;/text&gt;
        ///  &lt;subject&gt;
        ///    &lt;reference value=&quot;Patient/example&quot;/&gt;
        ///  &lt;/subject&gt;
        ///  &lt;code&gt;
        ///    &lt;coding&gt;
        ///      &lt;system value=&quot;http://snomed.info/sct&quot;/&gt;
        ///      &lt;code value=&quot;323418000&quot;/&gt;
        ///      &lt;display value=&quot;Fix me up&quot;/&gt;
        ///    &lt;/coding&gt;  
        ///  &lt;/code&gt;
        ///&lt;/ProcedureRequest&gt;.
        /// </summary>
        internal static string ProcedureRequest {
            get {
                return ResourceManager.GetString("ProcedureRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;Minimum and maximum # of times the element can appear in the instance&quot;&gt;Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferenceToParentElementWithShortDescription {
            get {
                return ResourceManager.GetString("ReferenceToParentElementWithShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;binding-description&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;p&gt;The codes SHALL be taken from &lt;a href=&quot;http://myResource&quot;&gt;http://myresource/&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ResourceBindingDescription {
            get {
                return ResourceManager.GetString("ResourceBindingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;The logical name of the element&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px&quot;&gt;
        ///      &lt;span title=&quot;Minimum and maximum # of times the element can appear in the instance&quot;&gt;Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SlicedSnapshotElementWithShortDescription {
            get {
                return ResourceManager.GetString("SlicedSnapshotElementWithShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;tr style=&quot;border: 1px #F0F0F0 solid; font-size: 11px; font-family: verdana; vertical-align: top;&quot;&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px; width:100px&quot;&gt;
        ///      &lt;span title=&quot;The path of the element&quot;&gt;Path&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;th class=&quot;hierarchy&quot; style=&quot;vertical-align:top; text-align:left; padding:0px 4px 0px 4px; width:100px&quot;&gt;
        ///      &lt;span title=&quot;The name of the valueSet&quot;&gt;Name&lt;/span&gt;
        ///    &lt;/th&gt;
        ///    &lt;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StructureDefinitionBindingsTabTable {
            get {
                return ResourceManager.GetString("StructureDefinitionBindingsTabTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;in-line-valueset&quot;&gt;
        ///  &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;br /&gt;
        ///    &lt;p&gt;This valueset includes all the codes for Administrative-Gender-DDMap-1-0: &lt;br /&gt;&lt;/p&gt;
        ///  &lt;/div&gt;
        ///  &lt;div class=&quot;codeSystem-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;table&gt;
        ///      &lt;tr class=&quot;table-header&quot;&gt;
        ///        &lt;th title=&quot;Code that identifies concept&quot; class=&quot;col-code&quot;&gt;Code&lt;/th&gt;
        ///        &lt;th title=&quot;Text to display to the user&quot; class=&quot;col-display&quot;&gt;Display&lt;/th&gt;
        ///      &lt;/tr&gt;
        ///      &lt;div class=&quot;table-rows&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValueSetCodeSystemNoDefinition {
            get {
                return ResourceManager.GetString("ValueSetCodeSystemNoDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;in-line-valueset&quot;&gt;
        ///  &lt;div xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;br /&gt;
        ///    &lt;p&gt;This valueset includes all the codes for Administrative-Gender-DDMap-1-0: &lt;br /&gt;&lt;/p&gt;
        ///  &lt;/div&gt;
        ///  &lt;div class=&quot;codeSystem-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;table&gt;
        ///      &lt;tr class=&quot;table-header&quot;&gt;
        ///        &lt;th title=&quot;Code that identifies concept&quot; class=&quot;col-code&quot;&gt;Code&lt;/th&gt;
        ///        &lt;th title=&quot;Text to display to the user&quot; class=&quot;col-display&quot;&gt;Display&lt;/th&gt;
        ///        &lt;th title=&quot;Formal definition&quot; class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValueSetcodeSystemTable {
            get {
                return ResourceManager.GetString("ValueSetcodeSystemTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;valueset-summary-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;table&gt;
        ///    &lt;tr class=&quot;valueset-summary-table-header&quot;&gt;
        ///      &lt;th title=&quot;The name of the element.&quot; class=&quot;col-name&quot;&gt;Name&lt;/th&gt;
        ///      &lt;th title=&quot;The value of the element.&quot; class=&quot;col-description&quot;&gt;Description&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Defining URL:&lt;/td&gt;
        ///      &lt;td&gt;http://fhir.nhs.net/ValueSet/administrative-gender-ddmap-1-0&lt;/td&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Name:&lt;/td&gt;
        ///        &lt;td&gt;Administrative-Gender-DDMap-1-0&lt;/td&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuesetFullSummaryTable {
            get {
                return ResourceManager.GetString("ValuesetFullSummaryTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;valueset-summary-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;table&gt;
        ///    &lt;tr class=&quot;valueset-summary-table-header&quot;&gt;
        ///      &lt;th title=&quot;The name of the element.&quot; class=&quot;col-name&quot;&gt;Name&lt;/th&gt;
        ///      &lt;th title=&quot;The value of the element.&quot; class=&quot;col-description&quot;&gt;Description&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Defining URL:&lt;/td&gt;
        ///      &lt;td&gt;http://fhir.nhs.net/ValueSet/administrative-gender-ddmap-1-0&lt;/td&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Name:&lt;/td&gt;
        ///        &lt;td&gt;Administrative-Gender-DDMap-1-0&lt;/td&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuesetSummaryNoCopyrightRow {
            get {
                return ResourceManager.GetString("ValuesetSummaryNoCopyrightRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;valueset-summary-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;table&gt;
        ///    &lt;tr class=&quot;valueset-summary-table-header&quot;&gt;
        ///      &lt;th title=&quot;The name of the element.&quot; class=&quot;col-name&quot;&gt;Name&lt;/th&gt;
        ///      &lt;th title=&quot;The value of the element.&quot; class=&quot;col-description&quot;&gt;Description&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Defining URL:&lt;/td&gt;
        ///      &lt;td&gt;http://fhir.nhs.net/ValueSet/administrative-gender-ddmap-1-0&lt;/td&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Name:&lt;/td&gt;
        ///        &lt;td&gt;Administrative-Gender-DDMap-1-0&lt;/td&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuesetSummaryNoLastupdatedRow {
            get {
                return ResourceManager.GetString("ValuesetSummaryNoLastupdatedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;valueset-summary-table&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;table&gt;
        ///    &lt;tr class=&quot;valueset-summary-table-header&quot;&gt;
        ///      &lt;th title=&quot;The name of the element.&quot; class=&quot;col-name&quot;&gt;Name&lt;/th&gt;
        ///      &lt;th title=&quot;The value of the element.&quot; class=&quot;col-description&quot;&gt;Description&lt;/th&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td&gt;Defining URL:&lt;/td&gt;
        ///      &lt;td&gt;http://fhir.nhs.net/ValueSet/administrative-gender-ddmap-1-0&lt;/td&gt;
        ///      &lt;tr&gt;
        ///        &lt;td&gt;Name:&lt;/td&gt;
        ///        &lt;td&gt;Administrative-Gender-DDMap-1-0&lt;/td&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValuesetSummaryNoOID {
            get {
                return ResourceManager.GetString("ValuesetSummaryNoOID", resourceCulture);
            }
        }
    }
}
